from fastapi import APIRouter, Request, UploadFile, File, Form, Depends
from fastapi.responses import HTMLResponse, JSONResponse
import logging
from pathlib import Path
from engine.llm import LLMAdapter
from core.parser import FileParser

router = APIRouter(prefix="/ai", tags=["AI Studio"])
logger = logging.getLogger(__name__)

@router.get("/studio", response_class=HTMLResponse)
async def ai_studio_page(request: Request):
    """Render the AI Studio UI."""
    return request.app.state.templates.TemplateResponse(
        "ai_studio.html",
        {"request": request}
    )

@router.post("/generate")
async def generate_tests(
    file: UploadFile = File(...),
    provider: str = Form(...),
    api_key: str = Form(...)
):
    """Generate tests from an uploaded file using the specified LLM."""
    try:
        content = await file.read()

        # 1. Parse the uploaded file into raw text steps
        raw_steps = FileParser.parse_file(file.filename, content)

        # 2. Use the LLM adapter to generate instructions
        adapter = LLMAdapter(provider=provider, api_key=api_key)
        instructions = adapter.generate_test_instructions(raw_steps)

        return JSONResponse(content={"status": "success", "instructions": instructions})

    except Exception as e:
        logger.error(f"Failed to generate tests: {e}")
        return JSONResponse(status_code=400, content={"status": "error", "message": str(e)})

from pydantic import BaseModel
from typing import List, Dict, Any
from core import database

class AIImportRequest(BaseModel):
    name: str
    url: str
    instructions: List[Dict[str, Any]]

@router.post("/import")
async def import_ai_test(request: Request, data: AIImportRequest):
    """Create a new test from AI generated instructions."""
    db_path = request.app.state.db_path
    try:
        test = await database.create_test(
            db_path,
            name=data.name,
            url=data.url,
            mode="recorded",
            description="Generated by AI Studio"
        )

        for i, step_data in enumerate(data.instructions):
            sequence = i + 1
            action = step_data.get("action", "assert_text")
            selector = step_data.get("selector", "")
            value = step_data.get("value", "")
            description = step_data.get("description", "")

            if not selector and action != "navigate":
                selector = "element"

            await database.create_step(
                db_path,
                test_id=test.id,
                sequence=sequence,
                action=action,
                selector=selector,
                value=value,
                description=description,
                is_sensitive=False
            )

        return {"status": "success", "test_id": test.id}
    except Exception as e:
        logger.error(f"Failed to import AI test: {e}")
        return JSONResponse(status_code=500, content={"status": "error", "message": str(e)})

import uuid
import asyncio
import os

# In-memory job tracker
record_jobs = {}

@router.post("/record-test")
async def start_record_test(
    request: Request,
    file: UploadFile = File(...),
    test_name: str = Form(...),
    test_url: str = Form(...),
    provider: str = Form(...),
    api_key: str = Form(...)
):
    """Start background autonomous recording."""
    # Lazy imports: loaded only when this endpoint is called,
    # so the module loads successfully even if browser_use is unavailable.
    from browser_use import Agent
    from langchain_openai import ChatOpenAI

    # Patch ChatOpenAI to provide a 'provider' attribute which browser-use 0.12+ expects
    if not hasattr(ChatOpenAI, 'provider'):
        ChatOpenAI.provider = property(lambda self: 'openai')

    content = await file.read()
    raw_steps = FileParser.parse_file(file.filename, content)

    job_id = str(uuid.uuid4())
    record_jobs[job_id] = {"status": "starting", "result": None}

    async def _run_in_thread():
        try:
            os.environ["OPENAI_API_KEY"] = api_key
            llm = ChatOpenAI(model="gpt-4o")
            task = f"Go to {test_url} and perform these steps:\n" + "\n".join(raw_steps)
            agent = Agent(task=task, llm=llm)
            history = await agent.run()
            record_jobs[job_id]["status"] = "done"
            record_jobs[job_id]["result"] = str(history.final_result()) if hasattr(history, 'final_result') else "completed"
        except Exception as e:
            record_jobs[job_id]["status"] = "error"
            record_jobs[job_id]["result"] = str(e)

    asyncio.create_task(_run_in_thread())
    return JSONResponse(content={"status": "started", "job_id": job_id})

@router.get("/record-status/{job_id}")
async def get_job_status(job_id: str):
    """Get the status of a background recording job."""
    job = record_jobs.get(job_id)
    if not job:
        return JSONResponse(status_code=404, content={"error": "Job not found"})
    return JSONResponse(content=job)
